name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # schedule:
  #   - cron: '30 5 * * 1,3'
  #test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish MyApp.csproj -c Release -o MyApplication
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyApplication
        path: MyApplication/**
        if-no-files-found: error
